# Generated by Django 3.2.8 on 2021-10-19 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wpensar', '0002_auto_20211019_0135'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compra',
            options={'ordering': ('-created',)},
        ),
    ]
