# Generated by Django 3.2.8 on 2021-10-19 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wpensar', '0004_alter_produto_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='name',
            field=models.CharField(help_text='Digite o nome do produto.', max_length=255, unique=True),
        ),
    ]
