# Generated by Django 3.2.8 on 2021-10-19 21:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wpensar', '0005_alter_produto_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='compra',
            name='name',
            field=models.CharField(help_text='Digite o nome identificador da compra.', max_length=255, unique=True),
        ),
    ]
